-- (( Groups ))--
require("prototypes.item-groups")
-- ))

-- (( Categories ))--
require("prototypes.recipe-categories")
require("prototypes.fuel-categories")
require("prototypes.module-categories")
-- ))

-- (( Circuit Connector Definitions )) --
require("prototypes.circuit-connector-definitions")
-- ))

-- (( Technology ))--
require("prototypes.technologies.antimony")
require("prototypes.technologies.silicon")
require("prototypes.technologies.thermal")
require("prototypes.technologies.eva")
require("prototypes.technologies.renewable")
require("prototypes.technologies.nonrenewable")
require("prototypes.technologies.anti-solar")
--require 'prototypes.technologies.lightning-catcher'
require("prototypes.technologies.tidal")
require("prototypes.technologies.solar")
require("prototypes.technologies.wind")
require("prototypes.technologies.geothermal")
require("prototypes.technologies.solarpower")
require("prototypes.technologies.thorium")
require("prototypes.technologies.coalplant")
require("prototypes.technologies.oilplant")
require("prototypes.technologies.gasplant")
require("prototypes.technologies.biomassplant")
require("prototypes.technologies.gd")
require("prototypes.technologies.lithium-processing")
require("prototypes.technologies.mof")
require("prototypes.technologies.intermetallics")
require("prototypes.technologies.battery")
require("prototypes.technologies.photonics")
require("prototypes.technologies.microwave-receiver")
require("prototypes.technologies.nuclear-power")
require("prototypes.technologies.carbon-fiber")
require("prototypes.technologies.erbium")
require("prototypes.technologies.nano-mesh")
require("prototypes.technologies.biofet")
require("prototypes.technologies.mega-farm-mova")
require("prototypes.technologies.nanozymes")
require("prototypes.technologies.advanced-robotics")
require("prototypes.technologies.rare-earth-tech")
require("prototypes.technologies.numal")
require("prototypes.technologies.sb-silicate")
require("prototypes.technologies.lithium-niobate")
require("prototypes.technologies.sc-engine")
require("prototypes.technologies.machine-components")
require("prototypes.technologies.tbp")
require("prototypes.technologies.acrylic")
require("prototypes.technologies.ammonium-oxalate")
require("prototypes.technologies.electric-energy-distribution")

-- ))

--(( RESOURCES ))--
require("prototypes.ores.geothermal-crack")
require("prototypes.ores.ree")
require("prototypes.ores.antimonium")
require("prototypes.ores.mova")

-- ))

-- (( ITEMs ))--
require("prototypes.items.items")
require("prototypes.items.items-wind")

-- (( FLUIDs ))--
require("prototypes.fluids.geothermal-water")
require("prototypes.fluids.sb-pulp-01")
require("prototypes.fluids.sb-pulp-02")
require("prototypes.fluids.sb-pulp-03")
require("prototypes.fluids.sb-pulp-04")
require("prototypes.fluids.sb-pulp-05")
require("prototypes.fluids.sb-11-conc")
require("prototypes.fluids.sb-conc")
require("prototypes.fluids.sb-final-conc")
require("prototypes.fluids.sb-low-conc")
require("prototypes.fluids.sb-58-conc")
require("prototypes.fluids.dowfroth-250")
require("prototypes.fluids.re-pulp-01")
require("prototypes.fluids.re-pulp-02")
require("prototypes.fluids.re-pulp-03")
require("prototypes.fluids.re-pulp-04")
require("prototypes.fluids.th-oxalate")
require("prototypes.fluids.stripped-th")
require("prototypes.fluids.gd-stripped-solution")
require("prototypes.fluids.trichlorosilane")
require("prototypes.fluids.pure-trichlorosilane")
require("prototypes.fluids.processed-fatty-acids")
require("prototypes.fluids.fatty-acids")
require("prototypes.fluids.middle-processed-lard")
require("prototypes.fluids.vinyl-acetate")
require("prototypes.fluids.perylene")
require("prototypes.fluids.organic-acid-anhydride")
require("prototypes.fluids.dcm")
require("prototypes.fluids.chloroauric-acid")
require("prototypes.fluids.teos")
require("prototypes.fluids.aniline")
require("prototypes.fluids.molten-nxzngd")
require("prototypes.fluids.molten-salt")
require("prototypes.fluids.hot-molten-salt")
require("prototypes.fluids.bca")
require("prototypes.fluids.clean-organic-pulp")
require("prototypes.fluids.organic-pulp")
require("prototypes.fluids.silicate-solution")
require("prototypes.fluids.filtered-silicate-solution")
require("prototypes.fluids.salt-solution")
require("prototypes.fluids.hot-solution")
require("prototypes.fluids.r1")
require("prototypes.fluids.r2")
require("prototypes.fluids.r3")
require("prototypes.fluids.r4")
require("prototypes.fluids.mother-liquor")
require("prototypes.fluids.anolyte")
require("prototypes.fluids.pre-fiber")
require("prototypes.fluids.nickel-carbonyl")
require("prototypes.fluids.allylamine")
require("prototypes.fluids.pre-phenothiazine")
require("prototypes.fluids.mova-pulp1")
require("prototypes.fluids.mova-pulp2")
require("prototypes.fluids.mova-pulp3")
require("prototypes.fluids.pre-enzyme")
require("prototypes.fluids.crude-enzyme")
require("prototypes.fluids.buffer-solution")
require("prototypes.fluids.numal-ink")
require("prototypes.fluids.void")
require("prototypes.fluids.mukmoux-oil")

require("prototypes.fluids.neutron")
--require 'prototypes.fluids.uranium'
--require 'prototypes.fluids.dirty-uranium'
require("prototypes.fluids.ac")
require("prototypes.fluids.plutonium-peroxide")
require("prototypes.fluids.purex-concentrate")
require("prototypes.fluids.purex-pu-concentrate")
require("prototypes.fluids.purex-raffinate")
require("prototypes.fluids.purex-u-concentrate")
require("prototypes.fluids.purex-waste")
require("prototypes.fluids.reactor-waste")
require("prototypes.fluids.butanol")
require("prototypes.fluids.phosphoryl-chloride")
require("prototypes.fluids.phosphorus-tricloride")
--require 'prototypes.fluids.tributyl-phosphate'
require("prototypes.fluids.uf6")
require("prototypes.fluids.puo2")
require("prototypes.fluids.antimony-phosphate")
require("prototypes.fluids.hydrofluoric-acid")
require("prototypes.fluids.molten-fluoride")
require("prototypes.fluids.fluorine-gas")
require("prototypes.fluids.hydrogen-sulfide")
require("prototypes.fluids.enriched-water")

-- ))

-- (( RECIPEs ))--
require("prototypes.recipes.recipes")
require("prototypes.recipes.recycling-recipes")
require("prototypes.recipes.recipes-eva")
require("prototypes.recipes.recipes-sb")
require("prototypes.recipes.recipes-si")
require("prototypes.recipes.recipes-gd")
require("prototypes.recipes.recipes-er")
require("prototypes.recipes.recipes-intermetallics")
require("prototypes.recipes.recipes-photonic-chip")
require("prototypes.recipes.recipes-extract-eyes")
require("prototypes.recipes.recipes-heat-exchanger")
require("prototypes.recipes.recipes-biomassplant")
require("prototypes.recipes.recipes-coalplant")
require("prototypes.recipes.recipes-gasplant")
require("prototypes.recipes.recipes-oilplant")
require("prototypes.recipes.recipes-nuclear-uranium")
require("prototypes.recipes.recipes-nuclear-mox")
require("prototypes.recipes.recipes-nuclear-thorium")
require("prototypes.recipes.recipes-nuclearplant")
require("prototypes.recipes.recipes-radioisotopes")
require("prototypes.recipes.recipes-mof")
require("prototypes.recipes.recipes-lithium")
require("prototypes.recipes.recipes-wind")
require("prototypes.recipes.recipes-carbonfiber")
require("prototypes.recipes.recipes-lrf")
require("prototypes.recipes.recipes-simik-boiler")
require("prototypes.recipes.nano-mesh")
require("prototypes.recipes.biofet")
require("prototypes.recipes.mova.recipes-mova-megafarm")
require("prototypes.recipes.mova.mova-processing")
require("prototypes.recipes.mirrors")

require("prototypes.recipes.numal.recipes-numal")
require("prototypes.recipes.numal.recipes-numal-modules")
require("prototypes.recipes.numal.recipes-numal-rendering")
require("prototypes.recipes.numal.recipes-numal-growth-enchancement")
require("prototypes.recipes.numal.recipes-numal-raising")

require("prototypes.recipes.recipes-fluorine")
-- ))

-- (( ROBOTS ))--
require("prototypes.robots.py-construction-robot-mk03")
require("prototypes.robots.py-logistic-robot-mk03")

-- (( BUILDINGS ))--
require("prototypes.buildings.hawt-turbine-mk01")
require("prototypes.buildings.hawt-turbine-mk02")
require("prototypes.buildings.hawt-turbine-mk03")
require("prototypes.buildings.hawt-turbine-mk04")
require("prototypes.buildings.vawt-turbine-mk01")
require("prototypes.buildings.vawt-turbine-mk02")
require("prototypes.buildings.vawt-turbine-mk03")
require("prototypes.buildings.vawt-turbine-mk04")
require("prototypes.buildings.steam-turbine-mk01")
require("prototypes.buildings.steam-turbine-mk02")
require("prototypes.buildings.steam-turbine-mk03")
require("prototypes.buildings.steam-turbine-mk04")
require("prototypes.buildings.solar-panel-mk01")
require("prototypes.buildings.solar-panel-mk02")
require("prototypes.buildings.solar-panel-mk03")
require("prototypes.buildings.solar-panel-mk04")
require("prototypes.buildings.lrf-mk01")
require("prototypes.buildings.lrf-panel-mk01")
require("prototypes.buildings.geothermal-plant-mk01")
require("prototypes.buildings.sut")
require("prototypes.buildings.mdh")
require("prototypes.buildings.anti-solar")
require("prototypes.buildings.solar-tower-megastructure")
require("prototypes.buildings.solar-tower-heilostat")
--require 'prototypes.buildings.lightning-catcher'
require("prototypes.buildings.nexelit-substation")
require("prototypes.buildings.nexelit-power-pole")
require("prototypes.buildings.solar-concentrator")
require("prototypes.buildings.stirling-concentrator")
require("prototypes.buildings.ree-mining-drill-mk01")
require("prototypes.buildings.ree-mining-drill-mk02")
require("prototypes.buildings.ree-mining-drill-mk03")
require("prototypes.buildings.ree-mining-drill-mk04")
require("prototypes.buildings.antimony-drill")
require("prototypes.buildings.nuclear-reactor-mk01")
require("prototypes.buildings.nuclear-reactor-mk02")
require("prototypes.buildings.nuclear-reactor-mk03")
require("prototypes.buildings.nuclear-reactor-mk04")
require("prototypes.buildings.nuclear-reactor-mox-mk01")
require("prototypes.buildings.nuclear-reactor-mox-mk02")
require("prototypes.buildings.nuclear-reactor-mox-mk03")
require("prototypes.buildings.nuclear-reactor-mox-mk04")
require("prototypes.buildings.neutron-absorber")
require("prototypes.buildings.neutron-moderator-mk01")
require("prototypes.buildings.neutron-moderator-mk02")
require("prototypes.buildings.neutron-moderator-mk03")
require("prototypes.buildings.neutron-moderator-mk04")
require("prototypes.buildings.accumulator-mk03")
require("prototypes.buildings.centrifuge-mk01")
require("prototypes.buildings.centrifuge-mk02")
require("prototypes.buildings.centrifuge-mk03")
require("prototypes.buildings.centrifuge-mk04")
require("prototypes.buildings.tidal-mk01")
require("prototypes.buildings.tidal-mk02")
require("prototypes.buildings.tidal-mk03")
require("prototypes.buildings.tidal-mk04")
require("prototypes.buildings.coal-powerplant")
require("prototypes.buildings.oil-powerplant")
require("prototypes.buildings.gas-powerplant")
require("prototypes.buildings.biomass-powerplant-mk01")
require("prototypes.buildings.biomass-powerplant-mk02")
require("prototypes.buildings.biomass-powerplant-mk03")
require("prototypes.buildings.biomass-powerplant-mk04")
require("prototypes.buildings.microwave-receiver")
require("prototypes.buildings.electric-boiler")
require("prototypes.buildings.aerial-mk01")
require("prototypes.buildings.aerial-mk02")
require("prototypes.buildings.aerial-mk03")
require("prototypes.buildings.aerial-mk04")
require("prototypes.buildings.aerial-base")
require("prototypes.buildings.simik-boiler")
require("prototypes.buildings.rtg")
require("prototypes.buildings.mk04-locomotive")
require("prototypes.buildings.mk04-cargo-wagon")
require("prototypes.buildings.mk04-fluid-wagon")
require("prototypes.buildings.multiblade-turbine-mk01")
require("prototypes.buildings.multiblade-turbine-mk03")
require("prototypes.buildings.numal-mk01")
require("prototypes.buildings.numal-mk02")
require("prototypes.buildings.numal-mk03")
require("prototypes.buildings.numal-mk04")
require("prototypes.buildings.uranium-mining-drill")

require("prototypes.buildings.heat-exchanger-mk02")
require("prototypes.buildings.heat-exchanger-mk03")
require("prototypes.buildings.heat-exchanger-mk04")

--(( ANIMATIONS ))
require("prototypes.animations.multiblade-turbine-mk01")
require("prototypes.animations.multiblade-turbine-mk03")
require("prototypes.animations.hawt-turbine-mk01")
require("prototypes.animations.hawt-turbine-mk02")
require("prototypes.animations.hawt-turbine-mk03")
require("prototypes.animations.hawt-turbine-mk04")

require("prototypes.decay.decay")

data.raw.fluid["crude-oil"].subgroup = "test"
data.raw.fluid["gasoline"].subgroup = "test"
data.raw.fluid["fatty-acids"].fuel_value = "1MJ"
data.raw.fluid["hydrogen"].fuel_value = "100kJ"
data.raw.fluid["pressured-hydrogen"].fuel_value = "1.25MJ"
