FLUID {
    type = "fluid",
    name = "molten-nxzngd",
    icon = "__pyalternativeenergygraphics__/graphics/icons/molten-nxzngd.png",
    icon_size = 64,
    default_temperature = 10,
    base_flow_rate = 100,
    --heat_capacity = "1kJ",
    base_color = {r = 0.168, g = 0.525, b = 0.509},
    flow_color = {r = 1, g = 1, b = 1},
    max_temperature = 100,
    gas_temperature = 15,
    subgroup = "py-alternativeenergy-intermetallics-3",
    order = "z",
}
