
--TECHNOLOGY--

--BUILDINDS--
RECIPE("natural-gas-seep-mk01"):add_ingredient({type = "item", name = "intermetallics", amount = 4})
RECIPE("bitumen-seep-mk01"):add_ingredient({type = "item", name = "intermetallics", amount = 5})
RECIPE("oil-sand-extractor-mk01"):add_ingredient({type = "item", name = "intermetallics", amount = 10})
RECIPE("tar-seep-mk01"):add_ingredient({type = "item", name = "intermetallics", amount = 5})
RECIPE("coalbed-mk01"):add_ingredient({type = "item", name = "intermetallics", amount = 8})
RECIPE("cracker-mk01"):add_ingredient({type = "item", name = "intermetallics", amount = 10})
RECIPE("gas-refinery-mk01"):add_ingredient({type = "item", name = "intermetallics", amount = 15})
RECIPE("heavy-oil-refinery-mk01"):add_ingredient({type = "item", name = "intermetallics", amount = 15})
RECIPE("lor-mk01"):add_ingredient({type = "item", name = "intermetallics", amount = 15})
RECIPE("pumpjack-mk01"):add_ingredient({type = "item", name = "intermetallics", amount = 5})
RECIPE("reformer-mk01"):add_ingredient({type = "item", name = "intermetallics", amount = 20})
RECIPE("tholin-atm-mk01"):add_ingredient({type = "item", name = "intermetallics", amount = 10})
RECIPE("tholin-plant-mk01"):add_ingredient({type = "item", name = "intermetallics", amount = 10})
RECIPE("upgrader-mk01"):add_ingredient({type = "item", name = "intermetallics", amount = 10})
RECIPE("guar-gum-plantation"):add_ingredient({type = "item", name = "intermetallics", amount = 10})
RECIPE("oil-boiler-mk01"):add_ingredient({type = "item", name = "intermetallics", amount = 10})
RECIPE("rhe"):add_ingredient({type = "item", name = "intermetallics", amount = 10})

RECIPE("natural-gas-seep-mk02"):add_ingredient({type = "item", name = "self-assembly-monolayer", amount = 4})
RECIPE("bitumen-seep-mk02"):add_ingredient({type = "item", name = "self-assembly-monolayer", amount = 5})
RECIPE("oil-sand-extractor-mk02"):add_ingredient({type = "item", name = "self-assembly-monolayer", amount = 10})
RECIPE("tar-seep-mk02"):add_ingredient({type = "item", name = "self-assembly-monolayer", amount = 5})
RECIPE("coalbed-mk02"):add_ingredient({type = "item", name = "self-assembly-monolayer", amount = 8})
RECIPE("cracker-mk02"):add_ingredient({type = "item", name = "self-assembly-monolayer", amount = 10})
RECIPE("gas-refinery-mk02"):add_ingredient({type = "item", name = "self-assembly-monolayer", amount = 15})
RECIPE("heavy-oil-refinery-mk02"):add_ingredient({type = "item", name = "self-assembly-monolayer", amount = 15})
RECIPE("lor-mk02"):add_ingredient({type = "item", name = "self-assembly-monolayer", amount = 15})
RECIPE("pumpjack-mk02"):add_ingredient({type = "item", name = "self-assembly-monolayer", amount = 5})
RECIPE("reformer-mk02"):add_ingredient({type = "item", name = "self-assembly-monolayer", amount = 20})
RECIPE("tholin-atm-mk02"):add_ingredient({type = "item", name = "self-assembly-monolayer", amount = 10})
RECIPE("tholin-plant-mk02"):add_ingredient({type = "item", name = "self-assembly-monolayer", amount = 10})
RECIPE("upgrader-mk02"):add_ingredient({type = "item", name = "self-assembly-monolayer", amount = 10})
RECIPE("sulfur-mine"):add_ingredient({type = "item", name = "self-assembly-monolayer", amount = 10})

RECIPE("natural-gas-seep-mk03"):add_ingredient({type = "item", name = "ns-material", amount = 4})
RECIPE("bitumen-seep-mk03"):add_ingredient({type = "item", name = "ns-material", amount = 5})
RECIPE("oil-sand-extractor-mk03"):add_ingredient({type = "item", name = "ns-material", amount = 10})
RECIPE("tar-seep-mk03"):add_ingredient({type = "item", name = "ns-material", amount = 5})
RECIPE("coalbed-mk03"):add_ingredient({type = "item", name = "ns-material", amount = 8})
RECIPE("cracker-mk03"):add_ingredient({type = "item", name = "ns-material", amount = 10})
RECIPE("gas-refinery-mk03"):add_ingredient({type = "item", name = "ns-material", amount = 15})
RECIPE("heavy-oil-refinery-mk03"):add_ingredient({type = "item", name = "ns-material", amount = 15})
RECIPE("lor-mk03"):add_ingredient({type = "item", name = "ns-material", amount = 15})
RECIPE("pumpjack-mk03"):add_ingredient({type = "item", name = "ns-material", amount = 5})
RECIPE("reformer-mk03"):add_ingredient({type = "item", name = "ns-material", amount = 20})
RECIPE("tholin-atm-mk03"):add_ingredient({type = "item", name = "ns-material", amount = 10})
RECIPE("tholin-plant-mk03"):add_ingredient({type = "item", name = "ns-material", amount = 10})
RECIPE("upgrader-mk03"):add_ingredient({type = "item", name = "ns-material", amount = 10})

RECIPE("natural-gas-seep-mk04"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 4})
RECIPE("bitumen-seep-mk04"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 5})
RECIPE("oil-sand-extractor-mk04"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 10})
RECIPE("tar-seep-mk04"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 5})
RECIPE("coalbed-mk04"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 8})
RECIPE("cracker-mk04"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 10})
RECIPE("gas-refinery-mk04"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 15})
RECIPE("heavy-oil-refinery-mk04"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 15})
RECIPE("lor-mk04"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 15})
RECIPE("pumpjack-mk04"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 5})
RECIPE("reformer-mk04"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 20})
RECIPE("tholin-atm-mk04"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 10})
RECIPE("tholin-plant-mk04"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 10})
RECIPE("upgrader-mk04"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 10})
RECIPE("retorter"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 10})
RECIPE("fracking-rig"):add_ingredient({type = "item", name = "metastable-quasicrystal", amount = 30})