name: Test

on:
  push:
    branches:
    - main
    - Frozen

permissions:
  contents: read

jobs:
  test-push:
    name: Push
    uses: pyanodon/pyanodontests/.github/workflows/pytest.yml@v1
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.sha }}
    secrets: inherit
